  
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: 'C:/positions.yaml'


scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
